version: 2

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{ .Tag }}

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}-{{ .Tag }}-{{ .Os }}_{{ .Arch }}
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - none*
    wrap_in_directory: true

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
