# Move up
up = ['k', 'up']
# Move down
down = ['j', 'down']
# Go to start
start = ['g', 'home']
# Go to end
end = ['G', 'end']
# Move to previous page
prev_page = ['b', 'pgup']
# Move to next page
next_page = ['f', 'pgdown']
# Focus on previous panel
prev_focus = ['h', 'shift+tab']
# Focus on next panel
next_focus = ['l', 'tab']
# 
# Add feed
add_feed = ['ctrl+n']
# Delete feed
delete_feed = ['ctrl+d']
# Rename feed
rename_feed = ['ctrl+m']
# Toogle starred status
toogle_starred = ['ctrl+s']
# Toogle read status
toogle_read = ['ctrl+r']
# Mark all items as read
mark_all_read = ['ctrl+R']
# Refresh feeds
refresh = ['ctrl+h']
# 
# Open in browser
open = ['ctrl+o']
# Export OPML
export = ['ctrl+e']
# Import OPML
import = ['ctrl+i']
# 
# Confirm
enter = ['enter']
# Cancel
esc = ['esc']
# Open config dir
open_dir = ['ctrl+p']
# Show help
help = ['?']
# Quit app
quit = ['ctrl+c']
